#!/usr/bin/env python3
"""Regenerate SCRAPERS.md from fleet.json (the single source of truth).

Usage:
    python tools/gen_scrapers_md.py

Run this after editing fleet.json (new scraper derived, status change, etc.)
so SCRAPERS.md never drifts from the manifest.
"""
from __future__ import annotations

import datetime
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
FLEET_JSON = ROOT / "fleet.json"
OUT_MD = ROOT / "SCRAPERS.md"

LANG_LABEL = {"js": "Node.js", "py": "Python"}


def load_fleet() -> dict:
    return json.loads(FLEET_JSON.read_text(encoding="utf-8"))

def row(s: dict) -> str:
    repo_url = f"https://github.com/{s['owner']}/{s['repo']}"
    lang = LANG_LABEL.get(s["language"], s["language"])
    ver = f"`@{s['template_version']}`" if s.get("template_version") else "-"
    status = s["status"]
    if s.get("notes"):
        status = f"{status} -- {s['notes']}"
    return (
        f"| {s['company']} | {s['brand']} | {s['cif'] or '-'} "
        f"| [{s['repo']}]({repo_url}) | {lang} | {ver} | {status} |"
    )


def build_markdown(fleet: dict) -> str:
    active = [s for s in fleet["scrapers"] if s["status"] == "active"]
    archived = [s for s in fleet["scrapers"] if s["status"] == "archived"]
    today = datetime.date.today().isoformat()

    lines = [
        "# Scraper registry",
        "",
        f"Generated from `fleet.json` on **{today}**. Do not edit this file by "
        "hand -- edit `fleet.json` and re-run `python tools/gen_scrapers_md.py`. "
        "See `ai/VERSIONING.md` for how to check what's actually pinned in a "
        "given repo if this drifts.",
        "",
        "| Company | Brand | CIF | Repo | Language | Template version | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    lines += [row(s) for s in active]
    lines += [
        "",
        f"All {len(active)} active repos above: branch protection (anti-accident: "
        "no force-push, no branch deletion, direct push to `main` still allowed) "
        "applied; weekly health-summary reusable workflow, template-sync-check, "
        "and `COMMIT_CHECKLIST.md` all present and pushed.",
    ]

    if archived:
        lines += [
            "",
            "## Also part of the fleet, archived (read-only)",
            "",
            "Confirmed to belong to the same \"zero bugs\" scope, but archived on "
            "GitHub (pushes rejected with 403) -- findings only, left as-is per "
            "an explicit decision to leave archived repos alone.",
            "",
            "| Repo | Language | Notes |",
            "|---|---|---|",
        ]
        for s in archived:
            repo_url = f"https://github.com/{s['owner']}/{s['repo']}"
            lang = LANG_LABEL.get(s["language"], s["language"])
            lines.append(
                f"| [{s['repo']}]({repo_url}) | {lang} | {s.get('notes', '')} |"
            )

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    fleet = load_fleet()
    OUT_MD.write_text(build_markdown(fleet), encoding="utf-8")
    n_active = sum(1 for s in fleet["scrapers"] if s["status"] == "active")
    n_archived = sum(1 for s in fleet["scrapers"] if s["status"] == "archived")
    print(f"Wrote {OUT_MD} ({n_active} active, {n_archived} archived)")


if __name__ == "__main__":
    main()
